#input("What's your name?")
#print(input("What's your name?") + "Hellow?")
#print(input("What's your name?"), "Hellow?")
#print(input("What's your name?"), "Hi")
#print("Thanks for attending")
#name = input("What's your name?")
#print("Dear. "+ name + " Nice to meet you")
#print("This is Python class")
#print("a basetball is $5000")
#print("How many do you want basketball?")
#count = int(input())
#print("Total price is", 5000*count) 
#f-string
print("A basketball os $50")
count = int(input("How many ball do you want?"))
print(f"Total price is {50*count} dollor.")
